# Generated by Django 4.2.1 on 2023-07-10 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], db_index=True, max_length=50)),
                ('bedrooms', models.PositiveBigIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('parking', models.BooleanField(blank=True, default=False, null=True)),
                ('furnished', models.BooleanField(blank=True, default=False, null=True)),
                ('offer', models.BooleanField(blank=True, db_index=True, default=False, null=True)),
                ('regularPrice', models.PositiveIntegerField()),
                ('discountedPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geolocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.geolocation')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing/images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.listing')),
            ],
        ),
    ]
